"""
Response Agent: assembles the final user-facing response.

Deliberately makes NO extra LLM call: the answer was already generated by
an upstream agent, and re-generating it would add cost, latency, and a
new chance to introduce unsupported claims. This agent adds safety
framing, sources, and emergency handling deterministically.
"""

import re

from app.models.schemas import AgentResult, SourceRef

DISCLAIMER = (
    "This is an educational demo, not medical advice. It cannot diagnose "
    "conditions or replace a qualified healthcare professional. Please "
    "consult a clinician for medical decisions."
)

EMERGENCY_BANNER = (
    "⚠️ If you or someone else may be having a medical emergency (for "
    "example chest pain, trouble breathing, stroke symptoms, severe "
    "bleeding, or thoughts of self-harm), contact your local emergency "
    "services immediately. This chatbot cannot help in emergencies."
)

_EMERGENCY_PATTERNS = [
    r"chest pain",
    r"can'?t breathe",
    r"cannot breathe",
    r"trouble breathing",
    r"difficulty breathing",
    r"stroke",
    r"heart attack",
    r"severe bleeding",
    r"unconscious",
    r"overdose",
    r"suicid",
    r"kill myself",
    r"self[- ]harm",
    r"seizure",
    r"anaphyla",
]
_EMERGENCY_REGEX = re.compile("|".join(_EMERGENCY_PATTERNS), re.IGNORECASE)


def detect_emergency(message: str) -> bool:
    """
    Simple keyword screen for emergency language. It is intentionally
    over-sensitive (false positives are acceptable, false negatives are not)
    and is NOT a substitute for real triage.
    """
    return bool(_EMERGENCY_REGEX.search(message or ""))


class ResponseAgent:
    name = "response_agent"

    def compose(
        self,
        answer: str,
        sources: list[SourceRef],
        agent: str,
        emergency: bool = False,
        include_disclaimer: bool = True,
    ) -> AgentResult:
        parts: list[str] = []

        if emergency:
            parts.append(EMERGENCY_BANNER)

        parts.append(answer.strip())

        if sources:
            unique = sorted({(s.source, s.chunk_index) for s in sources})
            src_lines = [f"- {name} (chunk {idx})" for name, idx in unique]
            parts.append("Sources:\n" + "\n".join(src_lines))

        if include_disclaimer:
            parts.append(f"_{DISCLAIMER}_")

        return AgentResult(
            answer="\n\n".join(parts),
            sources=sources,
            agent=agent,
            emergency_flag=emergency,
        )